name: conventional_commits

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  conventional_commits:
    runs-on: ubuntu-latest

    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
